variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  DEV_S3_BUCKET_NAME: $DEV_S3_BUCKET_NAME
  PROD_S3_BUCKET_NAME: $PROD_S3_BUCKET_NAME
  DEV_CLOUDFRONT_DISTRIBUTION_ID: $DEV_CLOUDFRONT_DISTRIBUTION_ID
  PROD_CLOUDFRONT_DISTRIBUTION_ID: $PROD_CLOUDFRONT_DISTRIBUTION_ID
alpha:
  stage: deploy
  image: telzee/website-builder
  script:
    - cd ./
    - n 14
    - yarn
    - CI=false yarn build
    - aws s3 rm s3://$DEV_S3_BUCKET_NAME/ --recursive --exclude "robots.txt"
    - aws s3 cp ./build/ s3://$DEV_S3_BUCKET_NAME --recursive
    - aws cloudfront create-invalidation --distribution-id $DEV_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
  only:
    - /^dev-v.*$/
  except:
    - branches
production:
  stage: deploy
  image: telzee/website-builder
  script:
    - cd ./
    - yarn
    - yarn build
    - aws s3 rm s3://$PROD_S3_BUCKET_NAME/ --recursive --exclude "robots.txt" --exclude "sitemap.xml"
    - aws s3 cp ./build/ s3://$PROD_S3_BUCKET_NAME --recursive
    - aws cloudfront create-invalidation --distribution-id $PROD_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
  only:
    - /^prod-v.*$/
  except:
    - branches